Repository hypertrace/hypertrace, pull requests merged in 2021-02, with the labels that each got.

#174 [chore] updates helm charts
  kubernetes/platform-services/Chart.yaml
Labels: automated pr, helm-updates, release

#175 Adds docker-compose file which runs hypertrace with postgres
  .github/workflows/docker-tests.yml
  docker/postgres/README.md
  docker/postgres/docker-compose.yml
Labels: docker, enhancement

#173 feat: Support for view-generator groups
  .github/graphql-e2e-tests/.gitignore
  .github/graphql-e2e-tests/src/main/java/org/hypertrace/e2etest/ApiTest.java
  kubernetes/clusters/dev/values.yaml
  kubernetes/clusters/standard/values.yaml
  kubernetes/platform-services/Chart.yaml
  kubernetes/platform-services/values.yaml
Labels: deployment, enhancement, helm

#177 ci: generates release notes with helm chart updates workflow
  .github/workflows/create-charts.sh
  .github/workflows/pull-release.yml
  RELEASE_NOTES.md
  kubernetes/tmp/compatibility_matrix.txt
Labels: ci, enhancement, release

#180 fix: helm values for hypertrace-view-generator
  kubernetes/clusters/dev/values.yaml
Labels: bug

#181 feat: adds postgres as a data store for helm deployment
  .github/workflows/create-charts.sh
  README.md
  kubernetes/README.md
  kubernetes/clusters/dev/values.yaml
  kubernetes/config/hypertrace.properties
  kubernetes/data-services/Chart.yaml
  kubernetes/data-services/postgres/values.yaml
  kubernetes/data-services/values.yaml
  kubernetes/hypertrace.sh
  kubernetes/platform-services/Chart.yaml
  kubernetes/platform-services/postgres/values.yaml
  kubernetes/platform-services/values.yaml
Labels: deployment, enhancement, helm

#182 chore: updates helm charts
  kubernetes/data-services/Chart.yaml
  kubernetes/platform-services/Chart.yaml
  kubernetes/tmp/compatibility_matrix.txt
  release_notes.md
Labels: automated pr, helm-updates, release

#183 fix: renames release notes file in script
  .github/workflows/create-charts.sh
  RELEASE_NOTES.md
  release_notes.md
Labels: chore

#185 feat: add macro services for query layer
  .github/workflows/create-charts.sh
  .github/workflows/pull-release.yml
  kubernetes/platform-services/Chart.yaml
  kubernetes/platform-services/postgres/values.yaml
  kubernetes/platform-services/values.yaml
Labels: deployment, enhancement

#189 fixes: adds e2e test script to enhance local testing & workflow for self-hosted runner
  .github/graphql-e2e-tests/ingest-traces.sh
  .github/graphql-e2e-tests/src/main/java/org/hypertrace/e2etest/ApiTest.java
  .github/graphql-e2e-tests/src/main/resources/e2e-test/number-of-spans.graphql
  .github/graphql-e2e-tests/src/main/resources/traces/trace-1.json
  .github/workflows/docker-tests.yml
  .github/workflows/hypertrace-release.yml
  .github/workflows/pull-release.yml
  .github/workflows/scripts/create-charts.sh
  .github/workflows/scripts/header.txt
  .github/workflows/scripts/inspect.sh
  .github/workflows/scripts/tests.sh
  kubernetes/README.md
  kubernetes/hypertrace-e2e-test.sh
  kubernetes/platform-services/values.yaml
Labels: bug, ci, deployment, enhancement

#188 chore: updates helm charts
  RELEASE_NOTES.md
  kubernetes/platform-services/Chart.yaml
  kubernetes/tmp/compatibility_matrix.txt
Labels: automated pr, helm-updates, release

#191 chore: cleanup package.json for ui e2e tests
  .github/ui-e2e-tests/package.json
Labels: chore

#195 chore: updates helm charts
  RELEASE_NOTES.md
  kubernetes/platform-services/Chart.yaml
  kubernetes/tmp/compatibility_matrix.txt
Labels: automated pr, helm-updates, release
